inputSpec: lottery.json
outputDir: lottery
generatorName: jaxrs-spec
additionalProperties:
    artifactId: lottery-service
    groupId: com.crazyfly
    library: quarkus
debugOperations: true
debugModels: true
templateDir: quarkus-template/templates