inputSpec: lottery.json
outputDir: lottery
generatorName: jaxrs-spec
additionalProperties:
    artifactId: lottery-service
    groupId: com.crazyfly
    modelPackage: com.crazyfly.models
    library: quarkus
    useSwaggerAnnotations: false
templateDir: quarkus-template/templates
