generatorName: jaxrs-spec
additionalProperties:
    modelPackage: com.crazyfly.models
    apiPackage: com.crazyfly.resources
    sourceFolder: src/main/java
    artifactId: lottery-service
    groupId: com.crazyfly
    library: quarkus
    useSwaggerAnnotations: false
    hideGenerationTimestamp: true
templateDir: quarkus/templates
files:
  crud_service.mustache:
    templateType: Model
    destinationFilename: CrudService.java
  openapi-generator-ignore.mustache:
    templateType: SupportingFiles
    destinationFilename: .openapi-generator-ignore
