generatorName: jaxrs-spec
additionalProperties:
    modelPackage: com.crazyfly.models
    apiPackage: com.crazyfly.resources
    sourceFolder: src/main/java
    artifactId: lottery-service
    groupId: com.crazyfly
    library: quarkus
    useSwaggerAnnotations: false
    hideGenerationTimestamp: true
templateDir: quarkus/templates
files:
  model_dto.mustache:
    folder: dto
    templateType: Model
    destinationFilename: Dto.java
  mappers.mustache:
    folder: src/main/java/com/crazyfly
    templateType: SupportingFiles
    destinationFilename: Mappers.java
  openapi-generator-ignore.mustache:
    templateType: SupportingFiles
    destinationFilename: .openapi-generator-ignore
